### ISSUE TITLE
Only working for PHP?

### ISSUE THREAD

**Issue by Chris2011** [tomor/netbeans-php-quickmethodjump#2]
I was searching for such feature long time ago as this is already implemented in IntelliJ. I created a ticket for this: https://netbeans.org/bugzilla/show_bug.cgi?id=245748
there you can see the attachment which I really would like to see in Netbeans. Your plugin is the first step to this. Is it possible to implement it in other languages too? If I understand it right, it ONLY search inside the current opened PHP file, right?

Cheers

Chris

**Comment by tomor** [comment]
Hi Chris,

yes it searches only in the current file.

This plugin is currently implemented in a really simple way. It was my first and so far the only try to implement a Netbeans plugin :) 
It doesn't use any Netbeans API for creation of the method list, it simply parses the file on it's own and searches for "function" keyword - that's why it currently works only for PHP +  javascript because of the "function" keyword.

I assume that Netbeans already has names of methods parsed in a structure as it shows them in the navigator. So if I knew how to access it, it would be really simple to make this plugin work for other languages too.
Another nice thing would be to use another thread for GUI so it's not stucked while it parses the file (you can see this behavior in big files).

Cheers, 
Tomas

**Comment by Chris2011** [comment]
But what you can do is, you can search for classes, functions, as well in java and in javascript for functions and php for classes too. You will not get the members maybe but methods and classes.

**Comment by tomor** [comment]
Purpose of this plugin is to be able to quickly jump to a method by it's name in the currently opened file, so I really don't want to search the classes. 
Or maybe I don't understand your point correctly?

**Comment by Chris2011** [comment]
What you created is a little navigator only for the current open file as the navigator is does this for every type he can solve in the opened file, like classes, interfaces, methods, functions, variables, fields etc. Yours is only for jump to method. My intentions is to jump to fields, classes, interfaces too inside the current open file as the navigator does. The navigator is not as flexible with the layout, because I have to show or hide him and reopen it when I have to search inside the file. I wanted the same functionality as in intelliJ for search in structure via Ctrl + F12 as you can see here: https://bugzilla-attachments-245748.netbeans.org/bugzilla/attachment.cgi?id=148093

This is only an example for JS but this is what would be nice to have in Netbeans.

**Comment by tomor** [comment]
Ok, now I understand.

I want to keep this plugin simple - just jumping to the methods. 

Even if I improve it, I don't have the intention to extend it to scan all other symbols (classes, interfaces, variables,...). It would make jumping to the methods by part of their names more complicated and slower.

**Comment by Chris2011** [comment]
I understand your point, maybe you can do another plugin for quick jump to symbols for each language. I think it depends on how you implements it but I think that this will not be slow. Because a big file should be handlebar fast too. And I mean really only in the opened file too, not in other files.

**Comment by tomor** [comment]
Ok, I will  think about it. I've added it to my "programming for fun" TODO list ;)
